---
title: "trabalho"
format: html
---

```{r}
library(readxl)
library(dplyr)
library(stargazer)
library(stringr)
library(writexl)
library(lmtest)
library(sandwich)
library(car)
```

```{r}
datasus <- read_excel('./datasus_4.xlsx')

head(datasus)
```

```{r}
finbra_2018 <- read_excel('./finbra.xlsx')
finbra_2017 <- read_excel('./finbra_2017.xlsx')
finbra_2016 <- read_excel('./finbra_2016.xlsx')

#queimadas <- read.csv('./queimadas.csv')
pib <- read.csv('./pib_municipal.csv')
pib_industria <- read.csv('./pib_industria.csv')
frota <- read_excel('./frota_carro.xlsx')
area_km2 <- read_excel('./area_km2.xlsx')
area_urbana <- read_excel('./area_urbana.xlsx')
#leitos <- read_excel('./leitos_p_mun.xlsx')
#demografia <- read_excel('./perfil_pop.xlsx')

head(pib)
```

```{r}
#demografia <- demografia %>%
#  mutate(
#    Cod.IBGE = str_extract(Município, "^\\d+"),
#    Cod.IBGE = as.numeric(Cod.IBGE),
#  )

#demografia$`60 ou mais` <- demografia$`60 a 69 anos` + demografia$`70 a 79 anos` + demografia$`80 anos e mais`

datasus <- datasus %>%
  mutate(
    Cod.IBGE = str_extract(Município, "^\\d+"),
    Cod.IBGE = as.numeric(Cod.IBGE),
    Município = substring(Município, 8, nchar(Município))
  )

area_km2 <- area_km2 %>% 
  mutate(
      Cod.IBGE = substr(as.character(Cod.IBGE), 1, nchar(as.character(Cod.IBGE)) - 1   ))

pib <- pib %>% 
  mutate(
      Cod.IBGE = substr(as.character(Código), 1, nchar(as.character(Código)) - 1   ))

pib_industria <- pib_industria %>% 
  mutate(
      Cod.IBGE = substr(as.character(Código), 1, nchar(as.character(Código)) - 1   ))

area_urbana <- area_urbana %>% 
  mutate(
      Cod.IBGE = substr(as.character(Cod.IBGE), 1, nchar(as.character(Cod.IBGE)) - 1   ))

#leitos <- leitos %>%
#  mutate(
#    Cod.IBGE = str_extract(Município, "^\\d+"),
#    Cod.IBGE = as.numeric(Cod.IBGE)
# )


padroniza_finbra <- function(df) {
  df %>%
    mutate(
      code_muni = Cod.IBGE,
      Cod.IBGE = substr(as.character(Cod.IBGE), 1, nchar(as.character(Cod.IBGE)) - 1  ),
      Cod.IBGE = as.numeric(Cod.IBGE),
      Valor = as.numeric(str_replace(Valor, ",", "."))
    )
}

finbra_2016 <- padroniza_finbra(finbra_2016)
finbra_2017 <- padroniza_finbra(finbra_2017)
finbra_2018 <- padroniza_finbra(finbra_2018)

head(finbra_2018)
```

```{r}
finbra_2016_sum <- finbra_2016 %>%
  group_by(Cod.IBGE, UF, População, code_muni) %>%
  summarise(Valor_2016 = sum(Valor, na.rm = TRUE), .groups = "drop")

finbra_2017_sum <- finbra_2017 %>%
  group_by(Cod.IBGE, UF, População, code_muni) %>%
  summarise(Valor_2017 = sum(Valor, na.rm = TRUE), .groups = "drop")

finbra_2018_sum <- finbra_2018 %>%
  group_by(Cod.IBGE, UF, População, code_muni) %>%
  summarise(Valor_2018 = sum(Valor, na.rm = TRUE), .groups = "drop")

head(finbra_2018_sum)
```

```{r}
df_final <- datasus %>%
  left_join(finbra_2018_sum, by = "Cod.IBGE")

df_final$Município <- paste(df_final$Município, df_final$UF, sep=" ")
frota$MUNICIPIO <- paste(frota$MUNICIPIO, frota$UF, sep=" ")

head(df_final)
```

```{r}
df_final <- merge(df_final, finbra_2017_sum[, c("Cod.IBGE", "Valor_2017")], by = "Cod.IBGE", all.x = TRUE)
df_final <- merge(df_final, finbra_2016_sum[, c("Cod.IBGE", "Valor_2016")], by = "Cod.IBGE", all.x = TRUE)
df_final <- merge(df_final, area_km2[, c("Cod.IBGE", "Area")], by = "Cod.IBGE", all.x = TRUE)
df_final <- merge(df_final, area_urbana[, c("Cod.IBGE", "AU")], by = "Cod.IBGE", all.x = TRUE)
df_final <- merge(df_final, pib[, c("Cod.IBGE", "PIB")], by = "Cod.IBGE", all.x = TRUE)
df_final <- merge(df_final, pib_industria[, c("Cod.IBGE", "Industria")], by = "Cod.IBGE", all.x = TRUE)
#df_final <- merge(df_final, leitos[, c("Cod.IBGE", "Quantidade_existente")], by = "Cod.IBGE", all.x = TRUE)
#df_final <- merge(df_final, demografia[, c("Cod.IBGE", "60 ou mais")], by = "Cod.IBGE", all.x = TRUE)
#df_final <- merge(df_final, queimadas[, c("Municipio", "FRP_medio")], by.x = "Município", by.y = "Municipio" , all.x = TRUE)
df_final <- merge(df_final, frota[, c("MUNICIPIO", "TOTAL")], by.x = "Município", by.y = "MUNICIPIO", all.x = TRUE)

head(df_final)
```

```{r}
df_final$Valor <- df_final$Valor_2016 + df_final$Valor_2017 + df_final$Valor_2018

#df_final$leitos_pc <- df_final$Quantidade_existente / df_final$População

#df_final$`60_ou_mais_pc` <- df_final$`60 ou mais` / df_final$População

df_final <- df_final %>%
  rename(Automoveis = TOTAL) %>%
  rename(Investimento = Valor)

df_final <- df_final %>%
  mutate(
    Regiao = case_when(
      UF %in% c("AC","AP","AM","PA","RO","RR","TO") ~ "Norte",
      UF %in% c("AL","BA","CE","MA","PB","PE","PI","RN","SE") ~ "Nordeste",
      UF %in% c("DF","GO","MT","MS") ~ "Centro-Oeste",
      UF %in% c("ES","MG","RJ","SP") ~ "Sudeste",
      UF %in% c("PR","RS","SC") ~ "Sul",
      TRUE ~ NA_character_
    )
  )

df_final = subset(df_final, select = -c(Valor_2016, Valor_2017, Valor_2018))

# Visualizar o resultado final
head(df_final)
```

```{r}
stargazer(df_final, type = 'text')
```

```{r}
write_xlsx(df_final, "base_trabalho.xlsx")
```
